### ISSUE TITLE
非常棒的想法 希望能继续推进下去

### ISSUE THREAD

**Issue by zlyon** [weilantian/langrensha#1]
非常棒的想法 希望能继续推进下去 itchat 线上的实例和说明太少了。

**Comment by zlyon** [comment]
在windows的CMD上运行 当分发完身份之后会报错。

**Comment by weilantian** [comment]
哈哈哈哈哈每一时间弄准备放弃了

**Comment by yyjlincoln** [comment]
谢谢鼓励!我们都是学生党,本来已经准备放弃这个项目了,如果有时间会重启这个项目,可能要一段时间,如果您不介意的话可以Watch这个项目,以后如果更新了我们会放到上面去.

**Comment by zlyon** [comment]
嗯，微信的网杀程序太少了。大部分都是面杀助手。也不是很好用。

**Comment by yyjlincoln** [comment]
目前有点时间...看一下能不能继续写下去...

**Comment by pengyaheng** [comment]
诶呀同学。。这程序是不是还有点问题。。咋设置参数呢？

**Comment by yyjlincoln** [comment]
现在程序处于暂停开发状态，不是特别清楚 好像在源代码有变量

pengyaheng <notifications@github.com> 于 2018年8月26日周日 14:18写道：

**Comment by yyjlincoln** [comment]
诸位，很久不见。
非常抱歉的说，该项目正式被放弃。

放弃的主要原因是微信对网页版微信API的封锁，导致此项目依赖库Itchat失效。同时，微信小程序的推出也直接削弱了该项目存在的意义。

次要原因是学业繁忙，并且也在着手写小程序，没有足够的精力维护该项目（之前已经停更接近两年）

作为Python与Github入门项目之一，这个项目对我的个人意义也很大。这个项目也会一直保留下去，但在可预见的未来不会有任何更新。你可以取消Watch了，或者也可以保留Watch直到某一天我们再次想起此项目，或者更换技术栈（如小程序）

总之，非常感谢你们对该项目的支持。
是时候告一段落了。

Thanks.
@yyjlincoln & @weilantian 
TS=1566132933.2354016
